// Shared topic pool — Foreigners in China edition.
// Topics are practical search queries users would realistically type.
// pickRandom(TOPIC_POOL, 5) is called on every reload so the 5 shown rotate automatically.

export const TOPIC_POOL = [
  // Visas & Legal
  'How to renew visa in China',
  'Work permit for foreigners 2025',
  'Student visa extension China',
  'Z visa requirements 2025',
  'How to get permanent residency China',
  'Overstay fine China what to do',
  'Residence permit renewal process',
  'How to change visa type China',
  'Emergency visa China',
  'Business visa to work visa China',
  'X1 visa requirements China',
  'How to register at local police China',
  'Visa run from China 2025',
  'How long can foreigners stay in China',
  'Embassy contacts China for Africans',
  'Chinese green card how to apply',
  'Deportation risk China foreigners',

  // Banking & Money
  'How to open bank account in China',
  'WeChat Pay for foreigners 2025',
  'Alipay without Chinese ID',
  'Sending money from China to Africa',
  'Best remittance app from China',
  'International wire transfer China',
  'Currency exchange best rate China',
  'Best bank for foreigners China',
  'Tax filing foreigner in China',
  'How to receive payment in China',
  'ICBC account for foreigners',
  'Bank of China foreigner account',
  'How to get Chinese bank card',
  'Transferring money to Nigeria from China',
  'Transferring money to Ghana from China',
  'Transferring money to Kenya from China',
  'Western Union China to Africa',
  'WorldRemit China to Africa',
  'Crypto trading from China',
  'Wise transfer from China',

  // Jobs & Income
  'Jobs for foreigners in China 2025',
  'Teaching English in China salary',
  'How to find remote work in China',
  'Freelancing from China legally',
  'Best paying jobs for expats China',
  'How to get a work permit fast',
  'Job interview tips China',
  'Side hustle ideas for foreigners China',
  'Dropshipping from China to Africa',
  'Online business ideas from China',
  'Content creator in China tips',
  'YouTube from China how to',
  'Selling on Amazon from China',
  'TikTok monetization from China',
  'How to invoice clients from China',

  // Housing & Accommodation
  'How to rent apartment in China',
  'Cheap apartments in Guangzhou',
  'Apartments for foreigners Shenzhen',
  'Apartment scams to avoid China',
  'How to break a lease China',
  'Best neighborhoods for Africans China',
  'Furnished apartments Yiwu',
  'Shared housing foreigners Beijing',
  'How to register address in China',
  'Short stay apartment China',
  'Apartments near Canton Fair',
  'Student dormitory China tips',
  'Landlord disputes China what to do',

  // Business & Trade
  'How to source products from China',
  'Canton Fair registration 2025',
  'Best markets in Guangzhou 2025',
  'Yiwu market sourcing guide',
  'How to find reliable suppliers China',
  'Freight forwarder recommendations China',
  'Shipping from China to Nigeria',
  'Shipping from China to Ghana',
  'Shipping from China to Kenya',
  'Shipping from China to South Africa',
  'Shipping from China to Ethiopia',
  'Import duties from China to Africa',
  'How to register a company in China',
  'Quality control tips when sourcing',
  '1688 buying guide for foreigners',
  'Taobao agent guide English',
  'Wholesale electronics China',
  'How to avoid scam suppliers',
  'MOQ negotiation tips China',
  'Sample order from China suppliers',
  'Guangzhou wholesale market guide',
  'Shenzhen electronics market tips',
  'How to find fashion suppliers China',
  'Hair extensions wholesale China',
  'Cosmetics suppliers China',
  'Best sourcing agents China',
  'Trade finance for Africa China',

  // Tech & Connectivity
  'Best VPN for China 2025',
  'Free VPN that works in China',
  'How to use WhatsApp in China',
  'How to access Instagram in China',
  'How to use Google in China',
  'Best SIM card for foreigners China',
  'How to get Chinese phone number',
  'DiDi taxi for foreigners guide',
  'Meituan food delivery in English',
  'Best translation app China',
  'WeChat group for Africans China',
  'How to set up Alipay step by step',
  'Internet speed China 2025',
  'Best router for China VPN',
  'Baidu Maps vs Google Maps',
  'How to buy train tickets online China',
  'Ctrip flight booking guide',
  'Pinduoduo in English guide',

  // Community & Social Life
  'African community in Guangzhou',
  'African community in Shanghai',
  'African community in Shenzhen',
  'African community in Beijing',
  'African community in Yiwu',
  'Nigerian community in China',
  'Ghanaian community in China',
  'East African community China',
  'Francophone Africans in China',
  'African church in Guangzhou',
  'African church in Beijing',
  'Halal food restaurants Guangzhou',
  'Halal food restaurants Shenzhen',
  'African hair salon Guangzhou',
  'African grocery store China',
  'African restaurant in Yiwu',
  'Making friends as a foreigner China',
  'Pan-African events China 2025',
  'Dating as a foreigner in China',
  'Cultural differences China Africa',
  'How to deal with racism in China',
  'Expat meetup events China',
  'African students in China tips',

  // Health & Wellbeing
  'English-speaking doctor in China',
  'International hospital Guangzhou',
  'International hospital Shanghai',
  'Health insurance for foreigners China',
  'Mental health support expats China',
  'Gym membership for foreigners China',
  'Medicine equivalents in China',
  'Medical check for visa China',
  'Emergency number for foreigners China',
  'Traditional Chinese medicine guide',
  'COVID rules China 2025',
  'Pregnancy care foreigner China',
  'Dental care China affordable',

  // Education & Learning
  'Chinese language school adults',
  'HSK exam preparation tips',
  'Learn Mandarin fast tips',
  'Scholarship for African students China',
  'University application China process',
  'TEFL certificate how to get China',
  'Best online Chinese lessons 2025',
  'Kids international school China',
  'How to enroll child in school China',
  'HSK 1 study guide',
  'Mandarin tones practice tips',
  'Pinyin learning guide',

  // Food & Lifestyle
  'Best halal restaurants Guangzhou',
  'African spices online China',
  'Cooking African food in China',
  'Vegetarian food in China guide',
  'Best street food cities China',
  'Food delivery app guide China',
  'Budget meals foreigner China',
  'African food recipes from China',
  'Where to find ugali ingredients China',
  'Where to find plantain China',
  'Nigerian food in Guangzhou',
  'Kenyan food in China',

  // Travel & Transport
  'Cheap flights China to Africa 2025',
  'High speed train booking guide China',
  'How to buy train tickets China',
  'Budget travel inside China',
  'Travel insurance for expats China',
  'Bringing family to China guide',
  'Chinese driving license for foreigners',
  'Airport transfer tips China',
  'Best cities to live in China for Africans',
  'Weekend trips from Guangzhou',
  'How to travel alone in China',
  'Border crossing China tips',
  'Cheapest flights Guangzhou to Africa',
  'Guangzhou to Lagos flight',
  'Guangzhou to Accra flight',
  'Guangzhou to Nairobi flight',
];

export function shuffle(arr) {
  const a = [...(arr || [])];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function pickRandom(arr, count) {
  return shuffle(arr).slice(0, count);
}
