// src/pages/cityguide/citydata.js
// Static city guide data for Hafrik – China cities

export const CITIES = [
  {
    id: 'guangzhou',
    name: 'Guangzhou',
    province: 'Guangdong',
    population: '18 Million',
    description: 'The trade capital of China. Home to the Canton Fair, Africa Town, and one of the largest African communities in Asia. Gateway for import/export business.',
    headerGrad: ['#c0392b', '#922b21'],
    image: 'https://images.unsplash.com/photo-1590073844006-33379778ae09?w=900&q=80',
    tags: ['Business', 'Factory', 'Foreigner Friendly'],
    emoji: '🏭',
    about: {
      history: 'One of China\'s oldest port cities, Guangzhou (formerly Canton) has been a trading hub for over 2,000 years. It was the first Chinese city to open to international trade and has maintained that spirit ever since.',
      economy: 'Guangdong Province\'s economic powerhouse. Driven by manufacturing, trade, logistics, and the famous Canton Fair held every April and October.',
      weather: 'Subtropical. Hot and humid summers (30–38°C), mild winters (8–18°C). Rain season: April–September.',
      lifestyle: 'Vibrant and diverse. Large African community (Xiaobei area). Rich Cantonese culture, street food, and a thriving nightlife.',
      transport: 'Extensive metro (14+ lines), Baiyun International Airport, high-speed rail to Shenzhen/HK/Beijing, DiDi, bus.',
      internationalCommunity: 'Largest African community in China concentrated in Xiaobei ("Chocolate City"). Many West African, Congolese, Nigerian, and Ghanaian communities.',
    },
    foreignerRating: { overall: 5, english: 3, costOfLiving: 3, jobs: 5, business: 5, nightlife: 5, safety: 4 },
    jobs: ['Trade Agent', 'Import/Export', 'Factory Sourcing', 'English Teacher', 'Translator', 'Modeling', 'DJ / Music', 'Football Coach', 'Marketing', 'Internship'],
    salary: [
      { role: 'English Teacher', range: '12,000 – 22,000 RMB' },
      { role: 'Trade Agent', range: '10,000 – 35,000 RMB' },
      { role: 'Factory Sourcing', range: '8,000 – 20,000 RMB' },
      { role: 'Office Job', range: '8,000 – 15,000 RMB' },
      { role: 'Part Time', range: '150 – 300 RMB/hr' },
    ],
    rent: [
      { type: 'Single Room', range: '800 – 1,500 RMB' },
      { type: 'Studio Apartment', range: '1,500 – 3,000 RMB' },
      { type: '1 Bedroom', range: '2,500 – 4,500 RMB' },
      { type: 'City Center', range: '4,000 – 8,000 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '15 – 35 RMB' },
      { item: 'Monthly transport', range: '150 – 300 RMB' },
      { item: 'Internet', range: '100 RMB' },
      { item: 'Phone plan', range: '80 RMB' },
      { item: 'Monthly expenses', range: '1,500 – 3,000 RMB' },
    ],
    food: { style: 'Cantonese cuisine — dim sum, seafood, rice noodles, roast meats.', spice: 'Mild to medium. Cantonese food is less spicy than Sichuan.', halal: 'Many halal restaurants in Xiaobei and Tianhe. Easy to find.', african: 'Xiaobei area has plenty of African restaurants — Nigerian, Congolese, Ghanaian.', western: 'Many options in Tianhe and Zhujiang New Town.' },
    transport: ['Metro (14+ lines)', 'Bus', 'DiDi & Taxi', 'Baiyun International Airport', 'Guangzhou South Railway Station', 'Guangzhou East Railway Station'],
    schools: ['American International School Guangzhou', 'British School Guangzhou', 'Utahloy International School', 'Guangdong Experimental High School International'],
    universities: ['Sun Yat-sen University', 'Jinan University', 'South China University of Technology', 'Guangdong University of Foreign Studies', 'Guangzhou University'],
    knownFor: ['Canton Fair', 'Wholesale markets', 'Import/export hub', 'African community (Xiaobei)', 'Factory sourcing', 'Trade agents', 'Fashion & goods'],
  },
  {
    id: 'shenzhen',
    name: 'Shenzhen',
    province: 'Guangdong',
    population: '17.5 Million',
    description: 'China\'s tech capital and innovation hub. Built from scratch in 40 years to become one of the most modern cities on earth. Next to Hong Kong.',
    headerGrad: ['#1565c0', '#0d47a1'],
    image: 'https://images.unsplash.com/photo-1591717564234-7fa0fe86f14c?w=900&q=80',
    tags: ['Tech', 'Business', 'Foreigner Friendly'],
    emoji: '🚀',
    about: {
      history: 'Just a fishing village in 1980, Shenzhen became China\'s first Special Economic Zone and transformed into a global tech and manufacturing powerhouse within decades.',
      economy: 'Home to Huawei, Tencent, DJI, ZTE, and thousands of tech startups. Also the world\'s largest electronics market (Huaqiangbei).',
      weather: 'Subtropical. Hot and humid summers, mild winters. Similar to Guangzhou.',
      lifestyle: 'Young, dynamic, and entrepreneurial. Large expat tech community. Excellent quality of life with modern infrastructure.',
      transport: 'Metro (16+ lines), Shenzhen Bao\'an International Airport, high-speed rail to Guangzhou/HK, DiDi.',
      internationalCommunity: 'Growing expat community of tech workers, entrepreneurs, and English teachers. Strong South and Southeast Asian presence.',
    },
    foreignerRating: { overall: 4, english: 4, costOfLiving: 2, jobs: 5, business: 5, nightlife: 4, safety: 5 },
    jobs: ['Software Developer', 'Product Manager', 'English Teacher', 'Electronics Sourcing', 'Marketing', 'Startup Founder', 'Trade Agent', 'Modeling'],
    salary: [
      { role: 'Software Developer', range: '25,000 – 60,000 RMB' },
      { role: 'English Teacher', range: '15,000 – 25,000 RMB' },
      { role: 'Electronics Sourcing', range: '10,000 – 25,000 RMB' },
      { role: 'Marketing', range: '12,000 – 22,000 RMB' },
      { role: 'Part Time', range: '150 – 350 RMB/hr' },
    ],
    rent: [
      { type: 'Single Room', range: '1,500 – 2,500 RMB' },
      { type: 'Studio Apartment', range: '2,500 – 4,500 RMB' },
      { type: '1 Bedroom', range: '4,000 – 7,000 RMB' },
      { type: 'City Center', range: '6,000 – 12,000 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '20 – 45 RMB' },
      { item: 'Monthly transport', range: '200 – 350 RMB' },
      { item: 'Internet', range: '100 RMB' },
      { item: 'Phone plan', range: '80 – 150 RMB' },
      { item: 'Monthly expenses', range: '2,500 – 5,000 RMB' },
    ],
    food: { style: 'Mix of Cantonese and national/international options.', spice: 'Mild. Many international restaurants available.', halal: 'Available in certain areas.', african: 'Some African restaurants, growing community.', western: 'Very well-catered. Many Western chains and expat-friendly restaurants.' },
    transport: ['Metro (16+ lines)', 'Bus', 'DiDi & Taxi', 'Shenzhen Bao\'an International Airport', 'Shenzhen North Railway Station'],
    schools: ['QSI International School', 'Shekou International School', 'Britannica International School', 'BASIS International School Shenzhen'],
    universities: ['Shenzhen University', 'Southern University of Science and Technology', 'Tsinghua University (SZ branch)', 'Peking University HSBC Business School'],
    knownFor: ['Tech startups', 'Huaqiangbei electronics market', 'Huawei & Tencent HQ', 'Innovation', 'Modern skyline', 'Next to Hong Kong'],
  },
  {
    id: 'shanghai',
    name: 'Shanghai',
    province: 'Shanghai Municipality',
    population: '24 Million',
    description: 'China\'s financial capital and most cosmopolitan city. Global hub for finance, fashion, media, and international business. The most international city in China.',
    headerGrad: ['#283593', '#1a237e'],
    image: 'https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?w=900&q=80',
    tags: ['Business', 'Finance', 'Foreigner Friendly'],
    emoji: '🌆',
    about: {
      history: 'Opened to foreign trade in 1842, Shanghai quickly became the Paris of the East. Today it is China\'s most internationally connected city with a legendary skyline.',
      economy: 'China\'s financial center. Home to the Shanghai Stock Exchange, hundreds of multinational corporations, and a thriving startup ecosystem.',
      weather: 'Four seasons. Hot humid summer (35°C+), cold winter (0–5°C), pleasant spring/autumn.',
      lifestyle: 'Highly international. Strong Western influence. World-class restaurants, art scene, nightlife, and shopping.',
      transport: 'World\'s busiest metro system (20 lines), 2 international airports (Pudong & Hongqiao), maglev train.',
      internationalCommunity: 'Largest expat community in China. French Concession is an expat hub. Many African, European, American, and Southeast Asian residents.',
    },
    foreignerRating: { overall: 5, english: 5, costOfLiving: 1, jobs: 5, business: 5, nightlife: 5, safety: 5 },
    jobs: ['Finance', 'English Teacher', 'Marketing', 'Software Developer', 'Fashion', 'Media', 'Trade Agent', 'Modeling', 'DJ / Music', 'Startup'],
    salary: [
      { role: 'English Teacher', range: '18,000 – 30,000 RMB' },
      { role: 'Finance / Banking', range: '25,000 – 80,000 RMB' },
      { role: 'Software Developer', range: '25,000 – 60,000 RMB' },
      { role: 'Marketing', range: '15,000 – 30,000 RMB' },
      { role: 'Part Time', range: '200 – 400 RMB/hr' },
    ],
    rent: [
      { type: 'Single Room', range: '2,500 – 4,000 RMB' },
      { type: 'Studio Apartment', range: '4,000 – 7,000 RMB' },
      { type: '1 Bedroom', range: '6,000 – 12,000 RMB' },
      { type: 'City Center', range: '10,000 – 20,000 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '25 – 60 RMB' },
      { item: 'Monthly transport', range: '200 – 400 RMB' },
      { item: 'Internet', range: '100 RMB' },
      { item: 'Phone plan', range: '80 – 120 RMB' },
      { item: 'Monthly expenses', range: '3,000 – 8,000 RMB' },
    ],
    food: { style: 'Everything — Shanghainese, dim sum, hotpot, and full international cuisine.', spice: 'Mild local food. Every cuisine type available.', halal: 'Available. Several halal restaurants and mosques.', african: 'Growing community. African restaurants in Hongkou and Jingan areas.', western: 'Excellent. French Concession is full of international restaurants and bars.' },
    transport: ['Metro (20 lines)', 'Bus', 'DiDi & Taxi', 'Maglev', 'Pudong International Airport', 'Hongqiao International Airport'],
    schools: ['Shanghai American School', 'British International School Shanghai', 'Dulwich College Shanghai', 'Concordia International School'],
    universities: ['Fudan University', 'Tongji University', 'Shanghai Jiao Tong University', 'East China Normal University', 'NYU Shanghai'],
    knownFor: ['The Bund', 'Financial hub', 'Fashion & media', 'Cosmopolitan lifestyle', 'Multinational corporations', 'French Concession'],
  },
  {
    id: 'beijing',
    name: 'Beijing',
    province: 'Beijing Municipality',
    population: '21.5 Million',
    description: 'China\'s capital. Political, cultural, and educational heart of the country. Rich in history with the Forbidden City, Great Wall, and a growing tech scene.',
    headerGrad: ['#bf360c', '#870000'],
    image: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=900&q=80',
    tags: ['Student', 'Business', 'Tech'],
    emoji: '🏯',
    about: {
      history: 'Capital of China for over 800 years. Home to the Forbidden City, Temple of Heaven, and the Great Wall — one of the most historically rich cities in the world.',
      economy: 'Government, technology (Zhongguancun Silicon Valley), education, and culture. Home to Baidu, ByteDance (TikTok), and major state companies.',
      weather: 'Cold winters (-10°C), hot dry summers (35°C). Dusty springs. Best time: September–November.',
      lifestyle: 'Political and cultural capital. Strong academic and diplomatic community. Good nightlife in Sanlitun.',
      transport: 'Metro (22+ lines), 2 major airports (Capital & Daxing), high-speed rail to all major cities.',
      internationalCommunity: 'Large diplomatic community. Wudaokou is the university/expat hub. Sanlitun for expat nightlife.',
    },
    foreignerRating: { overall: 4, english: 3, costOfLiving: 2, jobs: 4, business: 4, nightlife: 4, safety: 5 },
    jobs: ['English Teacher', 'Diplomat/Embassy', 'Software Developer', 'Trade Agent', 'Translator', 'Marketing', 'Internship', 'DJ', 'Modeling'],
    salary: [
      { role: 'English Teacher', range: '15,000 – 28,000 RMB' },
      { role: 'Software Developer', range: '20,000 – 55,000 RMB' },
      { role: 'Trade Agent', range: '12,000 – 30,000 RMB' },
      { role: 'Office Job', range: '10,000 – 20,000 RMB' },
      { role: 'Part Time', range: '150 – 300 RMB/hr' },
    ],
    rent: [
      { type: 'Single Room', range: '1,500 – 3,000 RMB' },
      { type: 'Studio Apartment', range: '3,000 – 5,500 RMB' },
      { type: '1 Bedroom', range: '5,000 – 9,000 RMB' },
      { type: 'City Center', range: '8,000 – 15,000 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '20 – 50 RMB' },
      { item: 'Monthly transport', range: '200 – 400 RMB' },
      { item: 'Internet', range: '100 RMB' },
      { item: 'Phone plan', range: '80 – 120 RMB' },
      { item: 'Monthly expenses', range: '2,500 – 5,000 RMB' },
    ],
    food: { style: 'Northern cuisine — Peking duck, dumplings, noodles, lamb skewers.', spice: 'Generally mild. Some spicy options.', halal: 'Niujie Muslim quarter has many halal restaurants.', african: 'Some African restaurants in Sanlitun and Wudaokou.', western: 'Excellent. Sanlitun and CBD areas have all major cuisines.' },
    transport: ['Metro (22+ lines)', 'Bus', 'DiDi & Taxi', 'Beijing Capital Airport (PEK)', 'Daxing International Airport (PKX)', 'Beijing South Railway Station'],
    schools: ['International School of Beijing (ISB)', 'British School of Beijing', 'Western Academy of Beijing', 'Dulwich College Beijing'],
    universities: ['Peking University', 'Tsinghua University', 'Renmin University', 'Beijing Normal University', 'Beijing Language and Culture University (BLCU)'],
    knownFor: ['Forbidden City', 'Great Wall', 'Tiananmen Square', 'Baidu & ByteDance HQ', 'Zhongguancun Tech Valley', 'Diplomatic hub'],
  },
  {
    id: 'hangzhou',
    name: 'Hangzhou',
    province: 'Zhejiang',
    population: '12 Million',
    description: 'Home of Alibaba and China\'s e-commerce revolution. Beautiful West Lake, thriving tech scene, and a high quality of life.',
    headerGrad: ['#00695c', '#004d40'],
    image: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=900&q=80',
    tags: ['Tech', 'Student', 'Business'],
    emoji: '🛒',
    about: {
      history: 'One of China\'s most beautiful historical cities, famous for West Lake. Also where Jack Ma founded Alibaba, making it China\'s e-commerce capital.',
      economy: 'E-commerce (Alibaba), fintech (Alipay), digital economy, and manufacturing. Rapidly growing startup scene.',
      weather: 'Four seasons. Hot humid summers, cool winters. Beautiful springs and autumns.',
      lifestyle: 'High quality of life. Blend of natural beauty (West Lake) and modern tech culture. Relatively relaxed pace.',
      transport: 'Metro, Xiaoshan International Airport, high-speed rail.',
      internationalCommunity: 'Growing expat community especially in tech. Many foreign students at Zhejiang University.',
    },
    foreignerRating: { overall: 4, english: 3, costOfLiving: 3, jobs: 4, business: 5, nightlife: 3, safety: 5 },
    jobs: ['Software Developer', 'E-commerce', 'English Teacher', 'Marketing', 'Internship at Alibaba', 'Trade Agent', 'Startup'],
    salary: [
      { role: 'English Teacher', range: '12,000 – 20,000 RMB' },
      { role: 'Software Developer', range: '20,000 – 50,000 RMB' },
      { role: 'E-commerce', range: '12,000 – 25,000 RMB' },
      { role: 'Marketing', range: '10,000 – 20,000 RMB' },
      { role: 'Part Time', range: '120 – 250 RMB/hr' },
    ],
    rent: [
      { type: 'Single Room', range: '1,200 – 2,500 RMB' },
      { type: 'Studio Apartment', range: '2,500 – 4,500 RMB' },
      { type: '1 Bedroom', range: '3,500 – 6,500 RMB' },
      { type: 'City Center', range: '5,000 – 10,000 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '18 – 40 RMB' },
      { item: 'Monthly transport', range: '150 – 280 RMB' },
      { item: 'Internet', range: '100 RMB' },
      { item: 'Phone plan', range: '80 RMB' },
      { item: 'Monthly expenses', range: '2,000 – 4,000 RMB' },
    ],
    food: { style: 'Zhejiang cuisine — fresh, mild, slightly sweet. Famous for Dongpo pork, West Lake fish.', spice: 'Mild.', halal: 'Some halal options available.', african: 'Limited but growing.', western: 'Good selection in expat areas near Alibaba campus.' },
    transport: ['Metro', 'Bus', 'DiDi', 'Xiaoshan International Airport', 'Hangzhou East Railway Station'],
    schools: ['Hangzhou International School', 'BASIS International School Hangzhou', 'Zhejiang University International Campus'],
    universities: ['Zhejiang University', 'Hangzhou Normal University', 'China Academy of Art'],
    knownFor: ['Alibaba HQ', 'E-commerce capital', 'West Lake (UNESCO)', 'Alipay & fintech', 'Digital economy', 'Startups'],
  },
  {
    id: 'nanjing',
    name: 'Nanjing',
    province: 'Jiangsu',
    population: '9.3 Million',
    description: 'Former capital of China. A major educational hub with rich history, affordable living, and a growing international community.',
    headerGrad: ['#6a1b9a', '#4a148c'],
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=900&q=80',
    tags: ['Student', 'Business'],
    emoji: '🎓',
    about: {
      history: 'Six times China\'s capital. Rich in Ming Dynasty history. Home to the Sun Yat-sen Mausoleum and Nanjing Massacre Memorial.',
      economy: 'Strong in electronics, petrochemicals, education, and emerging tech sectors.',
      weather: 'Hot humid summers, cold winters. Known for being one of China\'s "furnace cities" in summer.',
      lifestyle: 'University city atmosphere. Relaxed compared to Shanghai. Rich cultural life.',
      transport: 'Metro, Nanjing Lukou International Airport, high-speed rail.',
      internationalCommunity: 'Many foreign students due to strong university presence.',
    },
    foreignerRating: { overall: 3, english: 3, costOfLiving: 4, jobs: 3, business: 3, nightlife: 3, safety: 5 },
    jobs: ['English Teacher', 'Student Jobs', 'Internship', 'Translator', 'Tutor'],
    salary: [
      { role: 'English Teacher', range: '10,000 – 18,000 RMB' },
      { role: 'Office Job', range: '7,000 – 14,000 RMB' },
      { role: 'Tutoring', range: '150 – 300 RMB/hr' },
    ],
    rent: [
      { type: 'Single Room', range: '800 – 1,800 RMB' },
      { type: 'Studio Apartment', range: '2,000 – 3,500 RMB' },
      { type: '1 Bedroom', range: '2,500 – 4,500 RMB' },
      { type: 'City Center', range: '4,000 – 7,000 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '12 – 30 RMB' },
      { item: 'Monthly transport', range: '120 – 250 RMB' },
      { item: 'Internet', range: '100 RMB' },
      { item: 'Phone plan', range: '80 RMB' },
      { item: 'Monthly expenses', range: '1,500 – 3,000 RMB' },
    ],
    food: { style: 'Jiangsu cuisine — mild, sweet, delicate. Duck dishes are famous.', spice: 'Mild.', halal: 'Available.', african: 'Limited.', western: 'Good selection near universities.' },
    transport: ['Metro', 'Bus', 'DiDi', 'Nanjing Lukou Airport', 'Nanjing South Railway Station'],
    schools: ['Nanjing International School', 'Canadian International School Nanjing'],
    universities: ['Nanjing University', 'Southeast University', 'Nanjing University of Science and Technology', 'Hohai University'],
    knownFor: ['Historic capital', 'University hub', 'Ming Xiaoling Mausoleum', 'Affordable living', 'Rich cultural heritage'],
  },
  {
    id: 'chengdu',
    name: 'Chengdu',
    province: 'Sichuan',
    population: '21 Million',
    description: 'The city of pandas, spicy food, and leisure. Most laid-back megacity in China. Growing tech scene and one of the best places for quality of life.',
    headerGrad: ['#2e7d32', '#1b5e20'],
    image: 'https://images.unsplash.com/photo-1595435741763-cbfbfb0b3af3?w=900&q=80',
    tags: ['Student', 'Budget', 'Foreigner Friendly'],
    emoji: '🐼',
    about: {
      history: 'Over 2,300 years old. Capital of ancient Shu Kingdom. Famous for its relaxed teahouse culture and giant panda breeding base.',
      economy: 'Electronics, software, aviation, finance, and tourism. Home to Foxconn factories and growing tech industry.',
      weather: 'Mild and overcast. Rarely extreme hot or cold. High humidity. Limited sunshine (foggy).',
      lifestyle: 'Most relaxed megacity in China. Tea houses, mahjong, hot pot. Slow and enjoyable pace of life.',
      transport: 'Metro (13+ lines), Chengdu Tianfu International Airport (new, world\'s 5th largest), Shuangliu Airport.',
      internationalCommunity: 'Growing expat scene. Many foreigners come for the lifestyle, teaching jobs, and panda center.',
    },
    foreignerRating: { overall: 5, english: 3, costOfLiving: 5, jobs: 3, business: 3, nightlife: 4, safety: 5 },
    jobs: ['English Teacher', 'Panda Volunteer', 'Football Coach', 'Translator', 'Marketing', 'Student Jobs'],
    salary: [
      { role: 'English Teacher', range: '10,000 – 18,000 RMB' },
      { role: 'Marketing', range: '8,000 – 15,000 RMB' },
      { role: 'Office Job', range: '7,000 – 14,000 RMB' },
      { role: 'Part Time', range: '100 – 200 RMB/hr' },
    ],
    rent: [
      { type: 'Single Room', range: '500 – 1,200 RMB' },
      { type: 'Studio Apartment', range: '1,200 – 2,500 RMB' },
      { type: '1 Bedroom', range: '1,800 – 3,500 RMB' },
      { type: 'City Center', range: '3,000 – 6,000 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '10 – 25 RMB' },
      { item: 'Monthly transport', range: '100 – 200 RMB' },
      { item: 'Internet', range: '80 RMB' },
      { item: 'Phone plan', range: '60 – 80 RMB' },
      { item: 'Monthly expenses', range: '1,200 – 2,500 RMB' },
    ],
    food: { style: 'Sichuan cuisine — famous for numbing spice (mala), hotpot, mapo tofu.', spice: 'Very spicy! Sichuan peppercorn is unique and numbing.', halal: 'Available. Muslim quarter in the city.', african: 'Limited.', western: 'Good selection especially near Tongzilin and Kehua areas.' },
    transport: ['Metro (13+ lines)', 'Bus', 'DiDi', 'Chengdu Tianfu International Airport', 'Chengdu Shuangliu Airport', 'Chengdu East Railway Station'],
    schools: ['Chengdu International School', 'Leman International School', 'Western International School of Shanghai (Chengdu)'],
    universities: ['Sichuan University', 'University of Electronic Science and Technology of China', 'Southwest Jiaotong University', 'Chengdu University of Technology'],
    knownFor: ['Giant Panda Base', 'Sichuan hotpot', 'Relaxed lifestyle', 'Tea culture', 'Affordable living', 'Tianfu Square'],
  },
  {
    id: 'chongqing',
    name: 'Chongqing',
    province: 'Chongqing Municipality',
    population: '32 Million (municipality)',
    description: 'The most unique megacity in China. Built on mountains over two rivers. Famous for spicy hotpot, stunning night views, and rapid infrastructure development.',
    headerGrad: ['#e65100', '#bf360c'],
    image: 'https://images.unsplash.com/photo-1508163223045-1880bc36e222?w=900&q=80',
    tags: ['Budget', 'Business'],
    emoji: '🌉',
    about: {
      history: 'Wartime capital of China during WWII. Known as the Mountain City (山城). Now one of China\'s four directly-controlled municipalities.',
      economy: 'Automobile manufacturing, electronics, chemicals. Rapidly developing financial and logistics hub.',
      weather: 'Hot and foggy. One of China\'s "furnace cities". Very little sunshine. Humid year-round.',
      lifestyle: 'Dramatic landscape — roads and buildings stacked on hillsides. Known for beautiful women, spicy food, and intense nightlife.',
      transport: 'Metro, Jiangbei International Airport, river ferries (unique!), high-speed rail.',
      internationalCommunity: 'Smaller but growing expat community.',
    },
    foreignerRating: { overall: 3, english: 2, costOfLiving: 5, jobs: 3, business: 3, nightlife: 4, safety: 4 },
    jobs: ['English Teacher', 'Manufacturing', 'Translator', 'Football Coach'],
    salary: [
      { role: 'English Teacher', range: '8,000 – 16,000 RMB' },
      { role: 'Office Job', range: '6,000 – 12,000 RMB' },
      { role: 'Part Time', range: '80 – 180 RMB/hr' },
    ],
    rent: [
      { type: 'Single Room', range: '400 – 1,000 RMB' },
      { type: 'Studio Apartment', range: '1,000 – 2,000 RMB' },
      { type: '1 Bedroom', range: '1,500 – 3,000 RMB' },
      { type: 'City Center', range: '2,500 – 5,000 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '8 – 20 RMB' },
      { item: 'Monthly transport', range: '100 – 200 RMB' },
      { item: 'Internet', range: '80 RMB' },
      { item: 'Phone plan', range: '60 RMB' },
      { item: 'Monthly expenses', range: '1,000 – 2,200 RMB' },
    ],
    food: { style: 'Sichuan-style hotpot, spicy dishes, street food.', spice: 'Very spicy! Even spicier than Chengdu according to some.', halal: 'Some halal options available.', african: 'Very limited.', western: 'Limited but growing.' },
    transport: ['Metro', 'Bus', 'DiDi', 'River Ferries', 'Jiangbei International Airport', 'Chongqing North Railway Station'],
    schools: ['Chongqing No.1 Secondary School International', 'Liangjiang Sines International Academy'],
    universities: ['Chongqing University', 'Southwest University', 'Chongqing University of Posts and Telecommunications'],
    knownFor: ['Mountain city architecture', 'Hotpot capital', 'Night views at Hongyadong', 'Affordable living', 'Unique cable car transport', 'WWII history'],
  },
  {
    id: 'wuhan',
    name: 'Wuhan',
    province: 'Hubei',
    population: '13 Million',
    description: 'Capital of Central China. Major transportation hub and educational center. Known for universities and being at the heart of China\'s geography.',
    headerGrad: ['#4527a0', '#311b92'],
    image: 'https://images.unsplash.com/photo-1598887142487-3c854d51eabb?w=900&q=80',
    tags: ['Student', 'Budget'],
    emoji: '🌸',
    about: {
      history: 'One of the oldest cities in China with 3,500 years of history. Major port city on the Yangtze River. Center of the 1911 Revolution that ended imperial China.',
      economy: 'Steel, automobiles (DPCA factory), optics, biotechnology, and a strong education sector.',
      weather: 'Four seasons. Very hot humid summers, cold winters. Known as one of China\'s "furnace cities".',
      lifestyle: 'Large student population (1 million+). Vibrant university culture. Affordable and energetic.',
      transport: 'Metro, Wuhan Tianhe International Airport, high-speed rail hub.',
      internationalCommunity: 'Growing due to universities. Many African students especially in Wuhan University.',
    },
    foreignerRating: { overall: 3, english: 2, costOfLiving: 5, jobs: 3, business: 3, nightlife: 3, safety: 4 },
    jobs: ['English Teacher', 'Student Jobs', 'Tutor', 'Translator', 'Internship'],
    salary: [
      { role: 'English Teacher', range: '8,000 – 15,000 RMB' },
      { role: 'Office Job', range: '6,000 – 12,000 RMB' },
      { role: 'Part Time', range: '80 – 180 RMB/hr' },
    ],
    rent: [
      { type: 'Single Room', range: '500 – 1,200 RMB' },
      { type: 'Studio Apartment', range: '1,200 – 2,500 RMB' },
      { type: '1 Bedroom', range: '2,000 – 3,500 RMB' },
      { type: 'City Center', range: '3,000 – 5,500 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '8 – 20 RMB' },
      { item: 'Monthly transport', range: '100 – 200 RMB' },
      { item: 'Internet', range: '80 RMB' },
      { item: 'Phone plan', range: '60 RMB' },
      { item: 'Monthly expenses', range: '1,000 – 2,500 RMB' },
    ],
    food: { style: 'Hubei cuisine — hot dry noodles (re gan mian), duck neck, bean curd.', spice: 'Medium.', halal: 'Available.', african: 'Some around Wuhan University.', western: 'Moderate options near universities.' },
    transport: ['Metro', 'Bus', 'DiDi', 'Ferry on Yangtze', 'Wuhan Tianhe Airport', 'Wuhan Railway Station'],
    schools: ['Wuhan Foreign Languages School International', 'Guangai Middle School'],
    universities: ['Wuhan University', 'Huazhong University of Science and Technology (HUST)', 'Zhongnan University of Economics and Law', 'Wuhan University of Technology'],
    knownFor: ['Yangtze River crossing', '1 million students', 'Affordable city', 'Wuhan University cherry blossoms', 'Transportation hub', 'Hot dry noodles'],
  },
  {
    id: 'xian',
    name: "Xi'an",
    province: 'Shaanxi',
    population: '13 Million',
    description: 'Ancient capital of China. Home of the Terracotta Army. Where the Silk Road began. A city of 3,000 years of history and rich culture.',
    headerGrad: ['#795548', '#4e342e'],
    image: 'https://images.unsplash.com/photo-1609686506155-0877f2c24c3b?w=900&q=80',
    tags: ['Student', 'Budget'],
    emoji: '🏛️',
    about: {
      history: 'Capital of 13 dynasties. Starting point of the ancient Silk Road. Home to the Terracotta Warriors — one of the world\'s greatest archaeological wonders.',
      economy: 'Aerospace, military, electronics, tourism, and universities.',
      weather: 'Four seasons. Cold dry winters, hot dry summers. Best time: spring and autumn.',
      lifestyle: 'Deep historical atmosphere. Excellent street food. Muslim Quarter is a major attraction. Relatively affordable.',
      transport: 'Metro, Xi\'an Xianyang International Airport, high-speed rail.',
      internationalCommunity: 'Moderate. Many tourists and some long-term foreigners teaching at universities.',
    },
    foreignerRating: { overall: 3, english: 2, costOfLiving: 5, jobs: 3, business: 2, nightlife: 3, safety: 5 },
    jobs: ['English Teacher', 'Tourism', 'Translator', 'Student Jobs', 'Archaeology / Research'],
    salary: [
      { role: 'English Teacher', range: '8,000 – 15,000 RMB' },
      { role: 'Tourism / Guide', range: '5,000 – 12,000 RMB' },
      { role: 'Office Job', range: '6,000 – 11,000 RMB' },
    ],
    rent: [
      { type: 'Single Room', range: '400 – 1,000 RMB' },
      { type: 'Studio Apartment', range: '1,000 – 2,000 RMB' },
      { type: '1 Bedroom', range: '1,500 – 3,000 RMB' },
      { type: 'City Center', range: '2,500 – 5,000 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '8 – 20 RMB' },
      { item: 'Monthly transport', range: '80 – 180 RMB' },
      { item: 'Internet', range: '80 RMB' },
      { item: 'Phone plan', range: '60 RMB' },
      { item: 'Monthly expenses', range: '1,000 – 2,200 RMB' },
    ],
    food: { style: 'Northern Muslim influenced — lamb kebabs, roujiamo (Chinese burger), biangbiang noodles.', spice: 'Medium.', halal: 'Very available. Large Muslim Quarter (Huimin Jie) with halal food everywhere.', african: 'Very limited.', western: 'Limited, mostly near universities.' },
    transport: ['Metro', 'Bus', 'DiDi', "Xi'an Xianyang International Airport", "Xi'an North Railway Station"],
    schools: ['Xi\'an Gaoxin International School', 'High School Affiliated to Xi\'an Jiaotong University'],
    universities: ["Xi'an Jiaotong University", 'Northwestern Polytechnical University', 'Shaanxi Normal University', "Xi'an University of Foreign Languages"],
    knownFor: ['Terracotta Army', 'Ancient City Walls', 'Muslim Quarter', 'Silk Road origin', 'Biangbiang noodles', 'Tang Paradise'],
  },
  {
    id: 'tianjin',
    name: 'Tianjin',
    province: 'Tianjin Municipality',
    population: '14 Million',
    description: 'Major port city adjacent to Beijing. Industrial hub with European-style architecture from the colonial era. A more affordable alternative to Beijing.',
    headerGrad: ['#01579b', '#014f86'],
    image: 'https://images.unsplash.com/photo-1583417267826-aebc4d1542e1?w=900&q=80',
    tags: ['Business', 'Budget'],
    emoji: '⚓',
    about: {
      history: 'Major treaty port opened to foreign trade in 1858. Has European concession zones with French, Italian, British architecture still standing today.',
      economy: 'Port and logistics, manufacturing, petroleum, finance. Home to major car factories (Toyota, VW).',
      weather: 'Four seasons. Cold winters, hot summers. Windy in spring.',
      lifestyle: 'Quieter than Beijing with lower costs. Easy commute to Beijing by high-speed rail (30 min).',
      transport: 'Metro, Tianjin Binhai International Airport, high-speed rail to Beijing (30 min).',
      internationalCommunity: 'Moderate expat community. Many Korean and Japanese residents.',
    },
    foreignerRating: { overall: 3, english: 2, costOfLiving: 4, jobs: 3, business: 3, nightlife: 3, safety: 4 },
    jobs: ['English Teacher', 'Manufacturing', 'Trade Agent', 'Finance', 'Translator'],
    salary: [
      { role: 'English Teacher', range: '10,000 – 18,000 RMB' },
      { role: 'Office Job', range: '8,000 – 14,000 RMB' },
      { role: 'Manufacturing', range: '6,000 – 12,000 RMB' },
    ],
    rent: [
      { type: 'Single Room', range: '700 – 1,500 RMB' },
      { type: 'Studio Apartment', range: '1,500 – 3,000 RMB' },
      { type: '1 Bedroom', range: '2,500 – 4,500 RMB' },
      { type: 'City Center', range: '3,500 – 6,500 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '12 – 28 RMB' },
      { item: 'Monthly transport', range: '120 – 250 RMB' },
      { item: 'Internet', range: '80 RMB' },
      { item: 'Phone plan', range: '60 – 80 RMB' },
      { item: 'Monthly expenses', range: '1,500 – 3,000 RMB' },
    ],
    food: { style: 'Northern Chinese. Famous for "goubuli" steamed buns and Tianjin-style dishes.', spice: 'Mild.', halal: 'Available.', african: 'Very limited.', western: 'Moderate.' },
    transport: ['Metro', 'Bus', 'DiDi', 'Tianjin Binhai International Airport', 'Tianjin Railway Station', 'High-speed to Beijing (30 min)'],
    schools: ['Tianjin International School', 'BASIS International School Tianjin'],
    universities: ['Nankai University', 'Tianjin University', 'Tianjin Medical University'],
    knownFor: ['European concession architecture', 'Port city', 'Close to Beijing', 'Affordable living', 'Car manufacturing', 'Goubuli buns'],
  },
  {
    id: 'qingdao',
    name: 'Qingdao',
    province: 'Shandong',
    population: '9.5 Million',
    description: 'Coastal city with German colonial heritage. Home of Tsingtao Beer. Beautiful beaches, European architecture, and a relaxed seaside lifestyle.',
    headerGrad: ['#0277bd', '#01579b'],
    image: 'https://images.unsplash.com/photo-1567863966586-88c89d5b0d76?w=900&q=80',
    tags: ['Budget', 'Student'],
    emoji: '🍺',
    about: {
      history: 'German colonial period (1898–1914) left a lasting mark — European-style architecture, a brewing tradition, and orderly city planning.',
      economy: 'Shipping, trade, manufacturing, tourism, and the famous Tsingtao Brewery.',
      weather: 'Coastal climate. Mild summers (hot but breeze from sea), cold winters.',
      lifestyle: 'Relaxed beach city. Clean air, seaside walks, beer gardens. High quality of life for the cost.',
      transport: 'Metro, Qingdao Jiaodong International Airport (new), high-speed rail.',
      internationalCommunity: 'Small but growing. South Korean community is significant.',
    },
    foreignerRating: { overall: 3, english: 2, costOfLiving: 4, jobs: 2, business: 2, nightlife: 3, safety: 5 },
    jobs: ['English Teacher', 'Shipping/Logistics', 'Student Jobs', 'Tourism'],
    salary: [
      { role: 'English Teacher', range: '10,000 – 18,000 RMB' },
      { role: 'Logistics', range: '8,000 – 15,000 RMB' },
      { role: 'Office Job', range: '7,000 – 13,000 RMB' },
    ],
    rent: [
      { type: 'Single Room', range: '600 – 1,400 RMB' },
      { type: 'Studio Apartment', range: '1,500 – 2,800 RMB' },
      { type: '1 Bedroom', range: '2,200 – 4,000 RMB' },
      { type: 'City Center', range: '3,500 – 6,000 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '10 – 25 RMB' },
      { item: 'Monthly transport', range: '100 – 200 RMB' },
      { item: 'Internet', range: '80 RMB' },
      { item: 'Phone plan', range: '60 RMB' },
      { item: 'Monthly expenses', range: '1,200 – 2,800 RMB' },
    ],
    food: { style: 'Seafood-heavy Shandong cuisine. Fresh seafood, sea cucumbers, clams.', spice: 'Mild.', halal: 'Some options available.', african: 'Very limited.', western: 'Moderate, especially in tourist areas.' },
    transport: ['Metro', 'Bus', 'DiDi', 'Qingdao Jiaodong Airport', 'Qingdao North Railway Station'],
    schools: ['Qingdao No.9 High School International', 'Rego International School Qingdao'],
    universities: ['Ocean University of China', 'Qingdao University', 'China University of Petroleum'],
    knownFor: ['Tsingtao Beer', 'German architecture', 'Beaches', 'Sailing (2008 Olympics)', 'Seafood', 'Clean city'],
  },
  {
    id: 'suzhou',
    name: 'Suzhou',
    province: 'Jiangsu',
    population: '12 Million',
    description: 'China\'s Venice. Known for classical gardens, silk, and canals. Located 30 min from Shanghai by high-speed rail. Major manufacturing and expat hub.',
    headerGrad: ['#ad1457', '#880e4f'],
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=900&q=80',
    tags: ['Business', 'Factory', 'Student'],
    emoji: '🌿',
    about: {
      history: 'Over 2,500 years old. Famous for its classical gardens (UNESCO World Heritage), silk production, and beautiful canals.',
      economy: 'Suzhou Industrial Park (SIP) is one of China\'s most successful development zones. Manufacturing, biotech, high-tech industries.',
      weather: 'Four seasons. Similar to Shanghai. Hot humid summers, mild winters.',
      lifestyle: 'More relaxed than Shanghai. Mix of ancient charm and modern industry. Good expat infrastructure in the industrial park.',
      transport: 'Metro, Suzhou North Railway Station (30 min to Shanghai), DiDi.',
      internationalCommunity: 'Large expat community especially in Suzhou Industrial Park. Many Singaporean, European, and American professionals.',
    },
    foreignerRating: { overall: 4, english: 3, costOfLiving: 3, jobs: 4, business: 4, nightlife: 3, safety: 5 },
    jobs: ['Manufacturing Manager', 'English Teacher', 'Trade Agent', 'Software Developer', 'Logistics'],
    salary: [
      { role: 'English Teacher', range: '12,000 – 20,000 RMB' },
      { role: 'Manufacturing/Management', range: '15,000 – 35,000 RMB' },
      { role: 'Logistics', range: '10,000 – 18,000 RMB' },
    ],
    rent: [
      { type: 'Single Room', range: '1,000 – 2,000 RMB' },
      { type: 'Studio Apartment', range: '2,000 – 4,000 RMB' },
      { type: '1 Bedroom', range: '3,000 – 5,500 RMB' },
      { type: 'City Center', range: '4,500 – 8,000 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '15 – 35 RMB' },
      { item: 'Monthly transport', range: '150 – 250 RMB' },
      { item: 'Internet', range: '100 RMB' },
      { item: 'Phone plan', range: '80 RMB' },
      { item: 'Monthly expenses', range: '2,000 – 4,000 RMB' },
    ],
    food: { style: 'Jiangsu cuisine — mild, sweet, fresh. Squirrel-shaped mandarin fish is famous.', spice: 'Mild.', halal: 'Some options.', african: 'Limited.', western: 'Good options in SIP area.' },
    transport: ['Metro', 'Bus', 'DiDi', 'High-speed rail to Shanghai (30 min)', 'Suzhou Guangfu Airport'],
    schools: ['Dulwich College Suzhou', 'Suzhou Singapore International School', 'EtonHouse International School'],
    universities: ['Soochow University', 'Xi\'an Jiaotong-Liverpool University (XJTLU)', 'Suzhou University of Science and Technology'],
    knownFor: ['Classical gardens (UNESCO)', 'Silk production', 'Canals', 'Suzhou Industrial Park', 'Close to Shanghai', 'Biotech hub'],
  },
  {
    id: 'ningbo',
    name: 'Ningbo',
    province: 'Zhejiang',
    population: '9.4 Million',
    description: 'One of China\'s busiest ports and a key trade city. Strong manufacturing and logistics economy. Less known but important for import/export business.',
    headerGrad: ['#00838f', '#006064'],
    image: 'https://images.unsplash.com/photo-1635157896660-e98f7b8fdd62?w=900&q=80',
    tags: ['Business', 'Factory'],
    emoji: '🚢',
    about: {
      history: 'One of China\'s oldest port cities. Key trading port for centuries. Near Yiwu wholesale market.',
      economy: 'Port of Ningbo-Zhoushan is the world\'s busiest port by cargo tonnage. Plastics, chemicals, textile machinery manufacturing.',
      weather: 'Subtropical. Hot humid summers, mild winters. Similar to Hangzhou.',
      lifestyle: 'Business-focused. Quieter than Shanghai. Good quality of life.',
      transport: 'Metro, Ningbo Lishe International Airport, high-speed rail.',
      internationalCommunity: 'Small but growing. Business-oriented expats.',
    },
    foreignerRating: { overall: 3, english: 2, costOfLiving: 3, jobs: 3, business: 4, nightlife: 2, safety: 5 },
    jobs: ['Trade Agent', 'Logistics', 'English Teacher', 'Manufacturing', 'Sourcing Agent'],
    salary: [
      { role: 'English Teacher', range: '10,000 – 18,000 RMB' },
      { role: 'Trade/Logistics', range: '10,000 – 20,000 RMB' },
      { role: 'Manufacturing', range: '8,000 – 15,000 RMB' },
    ],
    rent: [
      { type: 'Single Room', range: '800 – 1,800 RMB' },
      { type: 'Studio Apartment', range: '1,800 – 3,500 RMB' },
      { type: '1 Bedroom', range: '2,500 – 4,500 RMB' },
      { type: 'City Center', range: '3,500 – 6,500 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '12 – 30 RMB' },
      { item: 'Monthly transport', range: '120 – 230 RMB' },
      { item: 'Internet', range: '80 RMB' },
      { item: 'Phone plan', range: '60 – 80 RMB' },
      { item: 'Monthly expenses', range: '1,500 – 3,000 RMB' },
    ],
    food: { style: 'Zhejiang seafood and mild flavours.', spice: 'Mild.', halal: 'Some options.', african: 'Very limited.', western: 'Limited.' },
    transport: ['Metro', 'Bus', 'DiDi', 'Ningbo Lishe Airport', 'Ningbo Railway Station', 'Ferry to Zhoushan islands'],
    schools: ['Ningbo International School', 'Ingram International School'],
    universities: ['Nottingham University Ningbo (UK university branch!)', 'Ningbo University', 'Zhejiang University Ningbo Institute'],
    knownFor: ["World's busiest port", 'Close to Yiwu market', 'Plastics & machinery', 'UK Nottingham University campus', 'Trade hub'],
  },
  {
    id: 'xiamen',
    name: 'Xiamen',
    province: 'Fujian',
    population: '5.2 Million',
    description: 'One of China\'s most beautiful and livable cities. Clean, coastal, relaxed. Famous for Gulangyu Island, excellent seafood, and a large overseas Chinese community.',
    headerGrad: ['#00796b', '#004d40'],
    image: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=900&q=80',
    tags: ['Budget', 'Student', 'Foreigner Friendly'],
    emoji: '🏝️',
    about: {
      history: 'Major port and trading hub. Strong connections to Southeast Asia — many overseas Chinese trace roots to Fujian/Xiamen.',
      economy: 'High-tech manufacturing, electronics, tourism. Xiamen Free Trade Zone.',
      weather: 'Subtropical. Warm winters, hot summers. Some typhoon risk in September.',
      lifestyle: 'One of China\'s most livable cities. Clean air, beautiful coastal scenery. Relaxed pace.',
      transport: 'Metro, Xiamen Gaoqi International Airport, ferry to Gulangyu Island.',
      internationalCommunity: 'Growing. Many Southeast Asian expats and some African traders.',
    },
    foreignerRating: { overall: 4, english: 3, costOfLiving: 4, jobs: 3, business: 3, nightlife: 3, safety: 5 },
    jobs: ['English Teacher', 'Tourism', 'Trade Agent', 'Student Jobs', 'Export'],
    salary: [
      { role: 'English Teacher', range: '10,000 – 18,000 RMB' },
      { role: 'Trade Agent', range: '8,000 – 18,000 RMB' },
      { role: 'Office Job', range: '7,000 – 14,000 RMB' },
    ],
    rent: [
      { type: 'Single Room', range: '800 – 1,800 RMB' },
      { type: 'Studio Apartment', range: '1,800 – 3,500 RMB' },
      { type: '1 Bedroom', range: '2,500 – 4,500 RMB' },
      { type: 'City Center', range: '3,500 – 6,500 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '12 – 30 RMB' },
      { item: 'Monthly transport', range: '100 – 200 RMB' },
      { item: 'Internet', range: '80 RMB' },
      { item: 'Phone plan', range: '60 RMB' },
      { item: 'Monthly expenses', range: '1,500 – 3,000 RMB' },
    ],
    food: { style: 'Fujian cuisine — seafood, oysters, satay noodles, light flavours.', spice: 'Mild.', halal: 'Some available.', african: 'Very limited.', western: 'Good options in tourist areas.' },
    transport: ['Metro', 'Bus', 'DiDi', 'Xiamen Gaoqi Airport', 'Xiamen North Railway Station', 'Ferry to Gulangyu'],
    schools: ['Xiamen International School', 'ULink College of Shanghai (Xiamen)'],
    universities: ['Xiamen University (Top 10 in China)', 'Huaqiao University', 'Jimei University'],
    knownFor: ['Gulangyu Island', 'Cleanest city in China', 'Seafood', 'Xiamen University campus (most beautiful)', 'Coastal lifestyle', 'Southeast Asian connection'],
  },
  {
    id: 'foshan',
    name: 'Foshan',
    province: 'Guangdong',
    population: '9.5 Million',
    description: 'The manufacturing powerhouse next to Guangzhou. China\'s capital for furniture, ceramics, and home appliances. Bruce Lee\'s hometown.',
    headerGrad: ['#e53935', '#c62828'],
    image: 'https://images.unsplash.com/photo-1565888636820-2c62b9671f3c?w=900&q=80',
    tags: ['Factory', 'Business'],
    emoji: '🪑',
    about: {
      history: 'Bruce Lee\'s father\'s hometown. Historic center of Cantonese culture, kung fu, and ceramics. Now one of China\'s most important manufacturing bases.',
      economy: 'Furniture (China\'s largest), ceramics, home appliances, metal products, textiles.',
      weather: 'Same subtropical climate as Guangzhou.',
      lifestyle: 'Industrial but livable. Connected to Guangzhou by metro. More affordable than Guangzhou.',
      transport: 'Metro connects to Guangzhou, Foshan Shadi Airport, DiDi.',
      internationalCommunity: 'Growing due to African and Middle Eastern traders coming for furniture and goods.',
    },
    foreignerRating: { overall: 3, english: 2, costOfLiving: 4, jobs: 3, business: 4, nightlife: 2, safety: 4 },
    jobs: ['Trade Agent', 'Factory Sourcing', 'Furniture Buyer', 'Import/Export', 'English Teacher'],
    salary: [
      { role: 'English Teacher', range: '10,000 – 16,000 RMB' },
      { role: 'Trade/Sourcing', range: '8,000 – 20,000 RMB' },
      { role: 'Manufacturing', range: '6,000 – 12,000 RMB' },
    ],
    rent: [
      { type: 'Single Room', range: '600 – 1,200 RMB' },
      { type: 'Studio Apartment', range: '1,200 – 2,500 RMB' },
      { type: '1 Bedroom', range: '2,000 – 3,500 RMB' },
      { type: 'City Center', range: '3,000 – 5,500 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '10 – 25 RMB' },
      { item: 'Monthly transport', range: '120 – 220 RMB' },
      { item: 'Internet', range: '80 RMB' },
      { item: 'Phone plan', range: '60 RMB' },
      { item: 'Monthly expenses', range: '1,200 – 2,500 RMB' },
    ],
    food: { style: 'Cantonese cuisine. Similar to Guangzhou.', spice: 'Mild.', halal: 'Some options.', african: 'Limited.', western: 'Limited.' },
    transport: ['Metro (connected to Guangzhou)', 'Bus', 'DiDi', 'Foshan Shadi Airport', 'Guangfo Metro'],
    schools: ['Foshan Nanhai Experimental School', 'Guangdong Experimental High School International Department'],
    universities: ['Foshan University', 'Guangdong University of Technology (Foshan Campus)'],
    knownFor: ['Furniture capital', 'Ceramics', 'Bruce Lee birthplace', 'Home appliances', 'Wholesale markets', 'Close to Guangzhou'],
  },
  {
    id: 'dongguan',
    name: 'Dongguan',
    province: 'Guangdong',
    population: '10.5 Million',
    description: 'Factory city between Guangzhou and Shenzhen. World\'s workshop for electronics, shoes, garments, and toys. Key for sourcing agents and traders.',
    headerGrad: ['#37474f', '#263238'],
    image: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=900&q=80',
    tags: ['Factory', 'Business'],
    emoji: '🏭',
    about: {
      history: 'Transformed from a farming town into a global manufacturing hub in 30 years. Now produces a significant percentage of the world\'s electronics and consumer goods.',
      economy: 'Electronics (smartphones, tablets), footwear, garments, furniture, toys manufacturing.',
      weather: 'Subtropical. Hot humid summers, mild winters.',
      lifestyle: 'Industrial city. Not particularly scenic but highly productive for business.',
      transport: 'Metro (to Guangzhou & Shenzhen), Dongguan Nancheng bus terminal, DiDi.',
      internationalCommunity: 'Many traders from Africa, Middle East, and Southeast Asia staying for business.',
    },
    foreignerRating: { overall: 2, english: 2, costOfLiving: 4, jobs: 3, business: 5, nightlife: 2, safety: 3 },
    jobs: ['Factory Sourcing', 'Quality Control', 'Trade Agent', 'English Teacher', 'Import/Export'],
    salary: [
      { role: 'English Teacher', range: '10,000 – 16,000 RMB' },
      { role: 'Sourcing Agent', range: '8,000 – 20,000 RMB' },
      { role: 'QC Inspector', range: '8,000 – 15,000 RMB' },
    ],
    rent: [
      { type: 'Single Room', range: '500 – 1,200 RMB' },
      { type: 'Studio Apartment', range: '1,200 – 2,200 RMB' },
      { type: '1 Bedroom', range: '1,800 – 3,500 RMB' },
      { type: 'City Center', range: '2,500 – 5,000 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '10 – 22 RMB' },
      { item: 'Monthly transport', range: '100 – 200 RMB' },
      { item: 'Internet', range: '80 RMB' },
      { item: 'Phone plan', range: '60 RMB' },
      { item: 'Monthly expenses', range: '1,200 – 2,500 RMB' },
    ],
    food: { style: 'Cantonese and factory cafeteria food. Good variety at low prices.', spice: 'Mild.', halal: 'Some.', african: 'Very limited.', western: 'Very limited.' },
    transport: ['Metro (Guangzhong-Zhuhai line)', 'Bus', 'DiDi', 'Near Guangzhou & Shenzhen airports'],
    schools: ['Dongguan Guangming School', 'EtonHouse International School Dongguan'],
    universities: ['Dongguan University of Technology', 'Guangdong Medical University'],
    knownFor: ['Electronics manufacturing', 'Footwear & garments', 'Factory sourcing hub', 'Cheap production', 'Quality control base'],
  },
  {
    id: 'zhuhai',
    name: 'Zhuhai',
    province: 'Guangdong',
    population: '2.4 Million',
    description: 'Clean coastal city next to Macau. Relaxed, scenic, and one of China\'s most livable cities. Special Economic Zone with growing aerospace and tech industries.',
    headerGrad: ['#00897b', '#00695c'],
    image: 'https://images.unsplash.com/photo-1519625658477-c66c9b5a9a6f?w=900&q=80',
    tags: ['Budget', 'Foreigner Friendly', 'Student'],
    emoji: '🌊',
    about: {
      history: 'One of China\'s first Special Economic Zones. Remains relatively small and clean compared to other Pearl River Delta cities.',
      economy: 'Aerospace (Zhuhai Airshow), software, chemicals, printing equipment, tourism (casino overflow from Macau).',
      weather: 'Subtropical. Warm and sunny. Some typhoon risk.',
      lifestyle: 'Very relaxed and clean. Beautiful coastal scenery. Much less congested than Guangzhou/Shenzhen.',
      transport: 'Local bus, DiDi, Zhuhai Jinwan Airport, ferry to Macau/HK, Hong Kong-Zhuhai-Macau Bridge.',
      internationalCommunity: 'Small but growing. Close proximity to Macau brings some international presence.',
    },
    foreignerRating: { overall: 4, english: 3, costOfLiving: 4, jobs: 2, business: 3, nightlife: 3, safety: 5 },
    jobs: ['English Teacher', 'Tech/Software', 'Tourism', 'Student Jobs'],
    salary: [
      { role: 'English Teacher', range: '10,000 – 18,000 RMB' },
      { role: 'Tech Job', range: '12,000 – 25,000 RMB' },
      { role: 'Office Job', range: '7,000 – 14,000 RMB' },
    ],
    rent: [
      { type: 'Single Room', range: '600 – 1,500 RMB' },
      { type: 'Studio Apartment', range: '1,500 – 3,000 RMB' },
      { type: '1 Bedroom', range: '2,500 – 4,500 RMB' },
      { type: 'City Center', range: '3,500 – 6,000 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '12 – 28 RMB' },
      { item: 'Monthly transport', range: '100 – 200 RMB' },
      { item: 'Internet', range: '80 RMB' },
      { item: 'Phone plan', range: '60 RMB' },
      { item: 'Monthly expenses', range: '1,500 – 3,000 RMB' },
    ],
    food: { style: 'Cantonese seafood. Fresh catches daily.', spice: 'Mild.', halal: 'Limited.', african: 'Very limited.', western: 'Some options near universities and Macau border.' },
    transport: ['Bus', 'DiDi', 'Zhuhai Jinwan Airport', 'Ferry to Macau (15 min)', 'Ferry to Hong Kong', 'HK-Zhuhai-Macau Bridge'],
    schools: ['Zhuhai International School', 'ULink College of Shanghai (Zhuhai)'],
    universities: ['United International College (UIC) — joint HK Baptist Univ', 'Zhuhai College of Jilin University', 'Beijing Normal University Zhuhai'],
    knownFor: ['Next to Macau', 'HK-Zhuhai-Macau Bridge', 'Cleanest city in PRD', 'Zhuhai Airshow', 'Coastal scenery', 'Relaxed lifestyle'],
  },
  {
    id: 'shenyang',
    name: 'Shenyang',
    province: 'Liaoning',
    population: '9 Million',
    description: 'Capital of Liaoning and largest city in Northeast China. Industrial city with Korean community, affordable living, and historical significance.',
    headerGrad: ['#546e7a', '#37474f'],
    image: 'https://images.unsplash.com/photo-1504093376055-b3094b605a30?w=900&q=80',
    tags: ['Budget', 'Student'],
    emoji: '🏔️',
    about: {
      history: 'Former capital of the Qing Dynasty before Beijing. Major industrial city during China\'s Communist era. Home to massive Soviet-era factories.',
      economy: 'Heavy industry, machinery, aerospace, steel. Economy has struggled since industrial reforms but is recovering.',
      weather: 'Cold continental. Very cold winters (-20°C), hot summers. Beautiful autumns.',
      lifestyle: 'Northeast Chinese culture — hearty food, direct people, strong community spirit. Very affordable.',
      transport: 'Metro, Shenyang Taoxian International Airport, high-speed rail.',
      internationalCommunity: 'Large Korean community. Some Japanese and other expats.',
    },
    foreignerRating: { overall: 2, english: 2, costOfLiving: 5, jobs: 2, business: 2, nightlife: 2, safety: 4 },
    jobs: ['English Teacher', 'Manufacturing', 'Korean/Japanese Translator', 'Student Jobs'],
    salary: [
      { role: 'English Teacher', range: '8,000 – 15,000 RMB' },
      { role: 'Office Job', range: '5,000 – 10,000 RMB' },
      { role: 'Manufacturing', range: '5,000 – 9,000 RMB' },
    ],
    rent: [
      { type: 'Single Room', range: '300 – 800 RMB' },
      { type: 'Studio Apartment', range: '800 – 1,800 RMB' },
      { type: '1 Bedroom', range: '1,200 – 2,500 RMB' },
      { type: 'City Center', range: '2,000 – 4,000 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '8 – 18 RMB' },
      { item: 'Monthly transport', range: '80 – 160 RMB' },
      { item: 'Internet', range: '60 RMB' },
      { item: 'Phone plan', range: '50 – 70 RMB' },
      { item: 'Monthly expenses', range: '800 – 2,000 RMB' },
    ],
    food: { style: 'Northeast cuisine — hearty, heavy, pork-based. Dongbei dumplings, stews.', spice: 'Mild with garlic and onion flavors.', halal: 'Limited.', african: 'Very limited.', western: 'Very limited.' },
    transport: ['Metro', 'Bus', 'DiDi', 'Shenyang Taoxian Airport', 'Shenyang North Railway Station'],
    schools: ['Shenyang International School'],
    universities: ['Northeastern University', 'Shenyang Pharmaceutical University', 'Liaoning University'],
    knownFor: ['Shenyang Imperial Palace (Qing)', 'Industrial history', 'Very affordable', 'Korean community', 'Northeast China culture'],
  },
  {
    id: 'harbin',
    name: 'Harbin',
    province: 'Heilongjiang',
    population: '9.9 Million',
    description: 'China\'s "Ice City". Famous for its spectacular ice sculpture festival, Russian heritage, and extreme winters. The coldest major city in China.',
    headerGrad: ['#1a237e', '#0d1b6b'],
    image: 'https://images.unsplash.com/photo-1551785716-8e0b11ae5d2e?w=900&q=80',
    tags: ['Student', 'Budget'],
    emoji: '❄️',
    about: {
      history: 'Strongly influenced by Russian culture — built as a railway junction by the Russian Empire in 1898. Architecture, food, and culture reflect this heritage.',
      economy: 'Agriculture, food processing, power equipment, pharmaceuticals. Economy has been transitioning from heavy industry.',
      weather: 'Extreme. Winters can reach -40°C. Summers mild (25°C). Spring and autumn very short.',
      lifestyle: 'Unique Sino-Russian culture. Cheap, safe, and friendly. World-famous Ice and Snow Festival (January).',
      transport: 'Metro, Harbin Taiping International Airport, high-speed rail.',
      internationalCommunity: 'Small. Some Russian tourists and residents. Growing student expat population.',
    },
    foreignerRating: { overall: 2, english: 2, costOfLiving: 5, jobs: 2, business: 2, nightlife: 2, safety: 5 },
    jobs: ['English Teacher', 'Russian Translator', 'Agriculture', 'Student Jobs'],
    salary: [
      { role: 'English Teacher', range: '8,000 – 14,000 RMB' },
      { role: 'Russian Interpreter', range: '8,000 – 18,000 RMB' },
      { role: 'Office Job', range: '5,000 – 10,000 RMB' },
    ],
    rent: [
      { type: 'Single Room', range: '300 – 800 RMB' },
      { type: 'Studio Apartment', range: '800 – 1,600 RMB' },
      { type: '1 Bedroom', range: '1,200 – 2,500 RMB' },
      { type: 'City Center', range: '2,000 – 4,000 RMB' },
    ],
    costOfLiving: [
      { item: 'Food per meal', range: '8 – 18 RMB' },
      { item: 'Monthly transport', range: '80 – 160 RMB' },
      { item: 'Internet', range: '60 RMB' },
      { item: 'Phone plan', range: '50 RMB' },
      { item: 'Monthly expenses', range: '800 – 2,000 RMB' },
    ],
    food: { style: 'Northeast cuisine with Russian influence. Bread, sausages, dumplings, hotpot.', spice: 'Mild.', halal: 'Limited.', african: 'Very limited.', western: 'Some Russian-style restaurants.' },
    transport: ['Metro', 'Bus', 'DiDi', 'Harbin Taiping Airport', 'Harbin West Railway Station'],
    schools: ['Harbin International School'],
    universities: ['Harbin Institute of Technology (Top 5 in China)', 'Harbin Engineering University', 'Heilongjiang University'],
    knownFor: ['Ice and Snow Festival', 'Russian architecture', 'Saint Sophia Cathedral', 'Extreme cold', 'Harbin Institute of Technology (HIT)', 'Ice cream culture'],
  },
];

// Filter tag options
export const FILTER_TAGS = [
  { key: 'all', label: 'All Cities' },
  { key: 'Business', label: 'Business' },
  { key: 'Tech', label: 'Tech' },
  { key: 'Factory', label: 'Factory' },
  { key: 'Student', label: 'Student' },
  { key: 'Budget', label: 'Budget' },
  { key: 'Foreigner Friendly', label: 'Expat Friendly' },
];
